version: "2.2"
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: jhipster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api-app:
    build:
      context: ../
      dockerfile: Dockerfile-Back
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:80
